apiVersion: v1
kind: Service
metadata:
  name: telemetryx-app-service
  namespace: sdsmcv-prd
spec:
  type: ClusterIP
  selector:
    app: telemetryx-app
  ports:
    - name: telemetryx-app
      protocol: TCP
      port: 80
      targetPort: 3000
